[database]
host="localhost"
port=5432
user="postgres"
pass="postgresFM7%YrmOj#rv@B!@xnWFu505"
name="postgres"
sslmode = "disable"

[api]
url="api.fluxojuridicos.com"
port=9000
jwt_secret="dz8o8zfdpnv2%-wcfe%$ugy-#!51be)ryvbb50tvo_v$ttan_+"

[cors]
allow_origins="*"
allow_methods="GET,POST,PUT,DELETE"
allow_headers="Origin,Content-Type,Accept,Authorization"
expose_headers="Content-Length"
allow_credentials=true
max_age=86400


[csrf]
secret = "3aeb8804f340b1327c38ff5d73edfcdac3ef74f33c1ef7bc5916fbcf7d77429b"




[waha]
waha_api_url="http://localhost:3000"
waha_api_key="your-secret-key"
webhook_forward_url="http://localhost:9000/automation-endpoint"
